// app/layout.jsx
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/footer"; // Import Footer component
import { ToastContainer } from 'react-toastify'; // Import ToastContainer
import 'react-toastify/dist/ReactToastify.css'; // Import toastify CSS

const montserrat = Montserrat({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Sosumi Blog App",
  description: "Created by Brian and Petra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {/* Font Awesome for icons */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" xintegrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6TaYFAaC7iSfLzVrmim8fceVCPQkXlTSg8K2fQ+i0eGtmZw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        {/* Favicon links generated by Next.js */}
        <link
            rel="icon"
            href="/icon?<generated>"
            type="image/<generated>"
            sizes="<generated>"
          />
      </head>
      <body className={`${montserrat.className} bg-gray-100 flex flex-col min-h-screen`}>
        <ToastContainer theme="dark" /> {/* ToastContainer for notifications */}
        <Header />
        {/* Main content area - removed vertical centering to allow content to flow naturally */}
        <main className="flex-grow w-full px-4 py-8 sm:px-6 sm:py-12">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
