import { Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Montserrat({
  subsets: ["latin"],
  weight: [400, 500, 600, 700]
});

const geistMono = Montserrat({
  subsets: ["latin"],
});

export const metadata = {
  title: "Sosumi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
